### ISSUE TITLE
Does not work with noise-protocol@2.0.0

### ISSUE THREAD

**Issue by sammacbeth** [geut/sodium-javascript-plus#2]
The most recent changes to https://github.com/emilbayes/noise-protocol/ seem to have broken this module. I'm currently getting an assertion error at the following line when the sodium-native import is replaced with sodium-javascript-plus: https://github.com/emilbayes/noise-protocol/blob/master/cipher.js#L8

**Comment by tinchoz49** [comment]
Hey sam! yes, because noise-protocol now is using `chacha` instead of `xchacha` I'm going to work on a new release this weekend to add support for chacha.

**Comment by sammacbeth** [comment]
Great! Thanks for your work on this!

**Comment by tinchoz49** [comment]
Glad to help. Thanks for using it :+1:

**Comment by tinchoz49** [comment]
@sammacbeth Can you try the version v0.0.6 ?
