### ISSUE TITLE
 Can't resolve '../sodium-modules'

### ISSUE THREAD

**Issue by DougAnderson444** [geut/sodium-javascript-plus#3]
When I run my code, I get
```
ERROR in ./node_modules/@geut/sodium-javascript-plus/lib/load-sodium-wasm.js
--
Module not found: 
Error: Can't resolve '../sodium-modules' in '/vercel/56e39944/node_modules/@geut/sodium-javascript-plus/lib'
```

It's weird because the json file is there. Should `.json` be added to the reference?

**Comment by tinchoz49** [comment]
Hey @DougAnderson444, how are you? 

That's weird, can you show me a reproducible example?

**Comment by DougAnderson444** [comment]
Yeah, it was weird. I was able to work around it by using an alias for the module in webpack. I think it was a webpack issue as opposed to a sodium issue, so I'll go ahead and close this.
